registry:
  image: nodesource/nsolid-registry
  container_name: registry
  net: "nsolid"
  ports:
    - 4001:4001
proxy:
  image: nodesource/nsolid-hub
  container_name: hub
  environment:
    - REGISTRY=registry:4001
    - NODE_DEBUG=nsolid
  net: "nsolid"
console:
  image: nodesource/nsolid-console
  container_name: console
  environment:
    - NODE_DEBUG=nsolid
    - NSOLID_APPNAME=console
    - NSOLID_HUB=registry:4001
  net: "nsolid"
  command: --hub hub:9000
  ports:
    - 3000:3000
app:
  image: nodesource/nsolid
  environment:
    - NODE_DEBUG=nsolid
    - NSOLID_APPNAME=in_docker
    - NSOLID_HUB=registry:4001
